name: Publish to npm

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: "22.14.0"
          registry-url: https://registry.npmjs.org
      - run: npm install -g npm@11.5.1
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public --provenance
